name = "astro-todoapp"
compatibility_date = "2024-12-26"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "todo-app-d1"
database_id = "42ff8001-5e70-4623-aeee-f8825ab1617c"
migrations_dir = "./migrations"